language : node_js
node_js :
 - 14
script:
  - docker build -t $DOCKER_USER/manager_server:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/manager_server:latest
  - docker tag $DOCKER_USER/manager_server:latest $DOCKER_USER/manager_server:`git describe --abbrev=0 --tags`
  - docker push $DOCKER_USER/manager_server:`git describe --abbrev=0 --tags`
